### ISSUE TITLE
About training time!

### ISSUE THREAD

**Issue by Z-Z-J** [nkolot/ProHMR#4]
Hello, I would like to ask about the GPU device used for training and the training time ? (2D pose lifting task)

**Comment by nkolot** [comment]
We used an RTX 2080Ti and training took about 6 hours.

**Comment by GloryyrolG** [comment]
> We used an RTX 2080Ti and training took about 6 hours.

The paper states "Training takes about 2.5 days on a NVIDIA RTX2080Ti using mixed precision". Does the code support multiple GPU training?
