### ISSUE TITLE
questions about getting 3d keypoints

### ISSUE THREAD

**Issue by visonpon** [nkolot/ProHMR#5]
Hi, thanks for your generous sharing of this wonderful work. I have tired on my own video and everything works fine.
But when I try to  extract the keypoints from the` opt_out['model_joints']`, all those points' coordinate values are so small and it seems these values are not the absolute 3d coordinates of those 44 points.
can you help tell me how to get the correct 3d keypoints? thanks~

**Comment by nkolot** [comment]
These are the 3D keypoint coordinates in meters. If you want a different unit, e.g. mm, just multiply them with 1000.

**Comment by visonpon** [comment]
it's my bad that my scripts have some bugs that result to this confuse and I have solved it, thanks~
but when I visualize those 3d keypoints ,it seems the roots' values(e.g, middle hip) are almost the same and the body doesn't move, so there isn't root motion prediction?

**Comment by nkolot** [comment]
Yes the keypoints are in the canonical frame, with the root being always at [0,0,0]. However to obtain the actual position in 3D space you can add the per frame `camera_translation` that we also include in the output.

**Comment by visonpon** [comment]
add `camera_translation` directly to the model_joints,  you mean ` opt_out['model_joints'][8:9,:] += opt_out['camera_translation'] `?

**Comment by nkolot** [comment]
`opt_out['camera_translation']` has dimensions `[N,3]`.
You should do `opt_out['model_joints'] += opt_out['camera_translation'].unsqueeze(1)`

**Comment by zhaishengfu** [comment]
Hello, I have one question for 3d points
![5_min_25fps_000000_fitting](https://user-images.githubusercontent.com/7630101/140445542-6d9a88cb-b75d-4861-9df2-8621e6d647ff.jpg)
as above image shows, your camera_translation should be in crop image? does this have influence in the full image. what i mean is, the camera_translation for the crop image is the same with for the full image??(and 3d keypoints?)

**Comment by nkolot** [comment]
The camera translation will not be the same. The 3D keypoints are root-relative, as returned by SMPL, so they don't include the translation. However if you fit on the crop vs in the full image the fitting results will be slightly different because of the scaling of the joints and the different camera model.

**Comment by zhaishengfu** [comment]
Ok， So If I want to drive model in unity， i only need care about the root translation，right？
and the final root translation is： camera_translation + original_root_translation？
the final root oriention is: global_orient

**Comment by nkolot** [comment]
Yes, correct.

**Comment by XiaobenLi00** [comment]
> Ok， So If I want to drive model in unity， i only need care about the root translation，right？ and the final root translation is： camera_translation + original_root_translation？ the final root oriention is: global_orient

Hi, thanks for the information you provided. I am wondering how you can get `original_root_translation`.
